server:
  port: 8081

spring:
  application:
    name: mcp-client
  profiles:
    active: msik

ai:
  chat:
    store:
      type: redis

deepseek:
#  baseUrl: https://api.deepseek.com
  baseUrl: https://lingsuan.top/v1
#  apiKey: sk-485e5c3ba56c461891c4230b8068bbe8
  apiKey: sk-215644dd3571137be747c24b2f083268110a8fa20cadf33c3b5f3da8551ca529
  modelName: gpt-5.5

qwen:
  apiKey: sk-ws-H.RPMILEX.jUpK.MEQCIH4Q5MgVgUksBh3P4P-MQXqPoa7EHv92JtJW4EkYd6NnAiA8-6jZdzYDdCUT0pqnKgm9SDEySP6OusTnj6174LDq-g
  modelName: qwen-plus