server:
  port: 8081

spring:
  application:
    name: mcp-client
  profiles:
    active: msik

ai:
  chat:
    store:
      type: redis

deepseek:
  baseUrl: https://api.deepseek.com/v1
  apiKey: sk-485e5c3ba56c461891c4230b8068bbe8
  modelName: deepseek-v4-pro

qwen:
  apiKey: sk-847dff9fa063420399a68d5a2cd1bdc2
  modelName: qwen-plus